
project_path: ./

datasets:
  n_classes: 3
  path: ./data/oral_dataset/
  img_path: images/
  filenames:
    dataset: oral1-12.json
    train: train.json
    val: validation.json
    test: test.json

prepare_dataset:
  seed: 42
  train_size: 0.8
  val_size: 0.9
  transform:
    width: 300 
    height: 300

training:
  lr: 8e-4
  epochs: 2
  batch: 64

models:
  path: models
  dropout: 0.15
  output_size: 10
  fc1_size: 32